### ISSUE TITLE
Microbiome over time - queries on input data

### ISSUE THREAD

**Issue by Slamazon4** [aametwally/MetaLonDA#10]
Hi @aametwally, 

I'm currently working on a project investigating potential changes in gut microbiome over time (within a 24 hour period). 

I feel this is likely more of an experimental design question but I just wanted to query whether you think your package may be appropriate to use on my data. 

I sampled from two cohorts of fish, one in summer and one in winter. 

I sampled 3 fish at 9 time points on each of these two occasions (calculated as hours post feed):

Summer - 1, 2, 3, 4, 5, 6, 8, 21 (hours)
Winter - 1, 2, 3, 4, 5, 6, 7, 23 (hours)

These are also not the same time points for each group (I was limited in my flexibility to access the animals for sampling at various times). 

I don't have a treatment vs control study design but I am assuming I should be able to compare the two cohorts as "groups"?

I am using Rstudio for all of my analysis and have my data organised within a phyloseq object - which I can obviously extract the abundance table from easily enough for the count = input. However, generating the time, group and ID inputs is a little confusing to me. 

I am unsure if you will be able to help me but any advice you might have on whether my data could be used with your package would be greatly appreciated.

**Comment by aametwally** [comment]
Hi @Slamazon4,

Sorry for the late response. Yea, MetaLonDA can be applied to your study design. Also, MetaLonDA takes care of the inconsistent sampling issue. You are right, the two groups in your case will be summer vs. winter.

Let's say your count table is organized as NxM matrix, where N represents the number of features, and M represents the number of samples. Then, Time, Group, and ID will be vectors with M elements. Time[i] represents the hour you have sampled sample i, Group[i] represents whether sample i has been taken in winter or summer, ID[i] represents the fish ID that sample i is taken from. i takes value from 1:M. 

Does that make sense? Please let me know if you have any questions.

**Comment by lixiaopi1985** [comment]
I think this post is similar to my question and it is not closed yet so I am posting here: I have a amplicon sequencing dataset with samples that I collected at 0, 1, 5, 12 days - 4 timepoints. The samples also contain 9 treatments. I want to see the effects of treatments as a function of time. Is MetaLonDA suitable for this kind of data? Thank you.

**Comment by aametwally** [comment]
Hi @lixiaopi1985,

Yea, MetaLonDA should work in your case. You would just need to do pairwise comparisons since MetaLonDA supports only testing two groups.

I'm gonna close this issue, but please feel free to open another one if you need any help!
