### ISSUE TITLE
Appropriate number of timepoint samples?

### ISSUE THREAD

**Issue by Malytherin** [aametwally/MetaLonDA#7]
Hi,

I am interested in using this package for a longitudinal study characterizing fecal microbiota over time as the feces decays. I subsampled fecal material once per day for 4-7 days (depending on the sample). I noticed in your package test data you have 10 time-points per sample. What do you think would be the minimum number of time points to use this package effectively? I'm worried I may not have enough time points for each of my samples (again, between 4 and 7).

Thank you!

**Comment by aametwally** [comment]
Sure, happy to help. 

In the example, I just used 10-time points to show the use case. 4-7 subsamples for each original sample should be sufficient for MetaLonDA analysis, given that you sample on a daily basis and hence no big lapse between consecutive samples. BTW, how many independent samples did you start with?  

Also, MetaLonDA is designed for longitudinal **differential** abundance testing, so you need to be comparing the trajectory of samples from two groups over time (e.g. healthy vs unhealthy). In this case, what are the two groups you have?

Best,

**Comment by malym** [comment]
Thank you for the quick reply!

Ah okay, so maybe this would not be helpful for this particular project. I have 8 independent samples (fecals) that I subsampled from for 4-7 days (weather permitting). I do not have 2 different groups. I see, so it is testing the differential abundance over time between two groups, not between the subsamples themselves (which is what I am interested in). That was my misunderstanding, sorry.

Thank you again for your response.
